name: reviewdog

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  reviewdog_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.3.1
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: reviewdog
        run: |
          reviewdog -reporter=github-pr-review -runners=deno,tsc -filter-mode=file -fail-on-error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
